/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionRouteImport } from './routes/version'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as MfaVerifyRouteImport } from './routes/mfa/verify'
import { Route as MfaSetupRouteImport } from './routes/mfa/setup'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettlementsRouteImport } from './routes/_authenticated/settlements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMerchantsRouteImport } from './routes/_authenticated/merchants'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions/$id'
import { Route as AuthenticatedSettingsTrustedDevicesRouteImport } from './routes/_authenticated/settings/trusted-devices'
import { Route as AuthenticatedMerchantsDashboardRouteImport } from './routes/_authenticated/merchants/dashboard'
import { Route as AuthenticatedMerchantsMerchantIdRouteImport } from './routes/_authenticated/merchants/$merchantId'

const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettlementsRoute =
  AuthenticatedSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMerchantsRoute = AuthenticatedMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSettingsTrustedDevicesRoute =
  AuthenticatedSettingsTrustedDevicesRouteImport.update({
    id: '/trusted-devices',
    path: '/trusted-devices',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMerchantsDashboardRoute =
  AuthenticatedMerchantsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMerchantsRoute,
  } as any)
const AuthenticatedMerchantsMerchantIdRoute =
  AuthenticatedMerchantsMerchantIdRouteImport.update({
    id: '/$merchantId',
    path: '/$merchantId',
    getParentRoute: () => AuthenticatedMerchantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/settlements': typeof AuthenticatedSettlementsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/_authenticated/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/_authenticated/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/version'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/merchants'
    | '/monitoring'
    | '/notifications'
    | '/rates'
    | '/risk'
    | '/settings'
    | '/settlements'
    | '/transactions'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/merchants/$merchantId'
    | '/merchants/dashboard'
    | '/settings/trusted-devices'
    | '/transactions/$id'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/version'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/merchants'
    | '/monitoring'
    | '/notifications'
    | '/rates'
    | '/risk'
    | '/settlements'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/'
    | '/merchants/$merchantId'
    | '/merchants/dashboard'
    | '/settings/trusted-devices'
    | '/transactions/$id'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/version'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/channels'
    | '/_authenticated/merchants'
    | '/_authenticated/monitoring'
    | '/_authenticated/notifications'
    | '/_authenticated/rates'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/settlements'
    | '/_authenticated/transactions'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/_authenticated/'
    | '/_authenticated/merchants/$merchantId'
    | '/_authenticated/merchants/dashboard'
    | '/_authenticated/settings/trusted-devices'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/settings/'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VersionRoute: typeof VersionRoute
  MfaSetupRoute: typeof MfaSetupRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/mfa/verify': {
      id: '/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/setup': {
      id: '/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/mfa/setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settlements': {
      id: '/_authenticated/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof AuthenticatedSettlementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchants': {
      id: '/_authenticated/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AuthenticatedMerchantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/settings/trusted-devices': {
      id: '/_authenticated/settings/trusted-devices'
      path: '/trusted-devices'
      fullPath: '/settings/trusted-devices'
      preLoaderRoute: typeof AuthenticatedSettingsTrustedDevicesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/merchants/dashboard': {
      id: '/_authenticated/merchants/dashboard'
      path: '/dashboard'
      fullPath: '/merchants/dashboard'
      preLoaderRoute: typeof AuthenticatedMerchantsDashboardRouteImport
      parentRoute: typeof AuthenticatedMerchantsRoute
    }
    '/_authenticated/merchants/$merchantId': {
      id: '/_authenticated/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AuthenticatedMerchantsMerchantIdRouteImport
      parentRoute: typeof AuthenticatedMerchantsRoute
    }
  }
}

interface AuthenticatedMerchantsRouteChildren {
  AuthenticatedMerchantsMerchantIdRoute: typeof AuthenticatedMerchantsMerchantIdRoute
  AuthenticatedMerchantsDashboardRoute: typeof AuthenticatedMerchantsDashboardRoute
}

const AuthenticatedMerchantsRouteChildren: AuthenticatedMerchantsRouteChildren =
  {
    AuthenticatedMerchantsMerchantIdRoute:
      AuthenticatedMerchantsMerchantIdRoute,
    AuthenticatedMerchantsDashboardRoute: AuthenticatedMerchantsDashboardRoute,
  }

const AuthenticatedMerchantsRouteWithChildren =
  AuthenticatedMerchantsRoute._addFileChildren(
    AuthenticatedMerchantsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsTrustedDevicesRoute: typeof AuthenticatedSettingsTrustedDevicesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsTrustedDevicesRoute:
    AuthenticatedSettingsTrustedDevicesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedMerchantsRoute: typeof AuthenticatedMerchantsRouteWithChildren
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSettlementsRoute: typeof AuthenticatedSettlementsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedMerchantsRoute: AuthenticatedMerchantsRouteWithChildren,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSettlementsRoute: AuthenticatedSettlementsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VersionRoute: VersionRoute,
  MfaSetupRoute: MfaSetupRoute,
  MfaVerifyRoute: MfaVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
