/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionRouteImport } from './routes/version'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as MfaVerifyRouteImport } from './routes/mfa/verify'
import { Route as MfaSetupRouteImport } from './routes/mfa/setup'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettlementsRouteImport } from './routes/_authenticated/settlements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMerchantsRouteImport } from './routes/_authenticated/merchants'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProvidersIndexRouteImport } from './routes/_authenticated/providers/index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels/index'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions/$id'
import { Route as AuthenticatedSettingsTrustedDevicesRouteImport } from './routes/_authenticated/settings/trusted-devices'
import { Route as AuthenticatedProvidersProviderIdChannelsRouteImport } from './routes/_authenticated/providers/channels'
import { Route as AuthenticatedMerchantsDashboardRouteImport } from './routes/_authenticated/merchants/dashboard'
import { Route as AuthenticatedMerchantsMerchantIdRouteImport } from './routes/_authenticated/merchants/$merchantId'
<<<<<<< HEAD
import { Route as AuthenticatedChannelsStrategyRouteImport } from './routes/_authenticated/channels/strategy'
import { Route as AuthenticatedChannelsRoutingRulesRouteImport } from './routes/_authenticated/channels/routing-rules'
import { Route as AuthenticatedChannelsHealthRouteImport } from './routes/_authenticated/channels/health'
import { Route as AuthenticatedChannelsChannelConfigsRouteImport } from './routes/_authenticated/channels/channel-configs'
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
import { Route as AuthenticatedChannelsChannelIdRouteImport } from './routes/_authenticated/channels.$channelId'
import { Route as AuthenticatedProvidersProviderIdChannelsRouteImport } from './routes/_authenticated/providers.$providerId.channels'

const VersionRoute = VersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettlementsRoute =
  AuthenticatedSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMerchantsRoute = AuthenticatedMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProvidersIndexRoute =
  AuthenticatedProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransactionsRoute,
  } as any)
const AuthenticatedSettingsTrustedDevicesRoute =
  AuthenticatedSettingsTrustedDevicesRouteImport.update({
    id: '/trusted-devices',
    path: '/trusted-devices',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProvidersProviderIdChannelsRoute =
  AuthenticatedProvidersProviderIdChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)
const AuthenticatedMerchantsDashboardRoute =
  AuthenticatedMerchantsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedMerchantsRoute,
  } as any)
const AuthenticatedMerchantsMerchantIdRoute =
  AuthenticatedMerchantsMerchantIdRouteImport.update({
    id: '/$merchantId',
    path: '/$merchantId',
    getParentRoute: () => AuthenticatedMerchantsRoute,
  } as any)
<<<<<<< HEAD
const AuthenticatedChannelsStrategyRoute =
  AuthenticatedChannelsStrategyRouteImport.update({
    id: '/strategy',
    path: '/strategy',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsRoutingRulesRoute =
  AuthenticatedChannelsRoutingRulesRouteImport.update({
    id: '/routing-rules',
    path: '/routing-rules',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsHealthRoute =
  AuthenticatedChannelsHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedChannelsChannelConfigsRoute =
  AuthenticatedChannelsChannelConfigsRouteImport.update({
    id: '/channel-configs',
    path: '/channel-configs',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
const AuthenticatedChannelsChannelIdRoute =
  AuthenticatedChannelsChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedChannelsRoute,
  } as any)
const AuthenticatedProvidersProviderIdChannelsRoute =
  AuthenticatedProvidersProviderIdChannelsRouteImport.update({
    id: '/$providerId/channels',
    path: '/$providerId/channels',
    getParentRoute: () => AuthenticatedProvidersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/rates': typeof AuthenticatedRatesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
<<<<<<< HEAD
  '/channels/channel-configs': typeof AuthenticatedChannelsChannelConfigsRoute
  '/channels/health': typeof AuthenticatedChannelsHealthRoute
  '/channels/routing-rules': typeof AuthenticatedChannelsRoutingRulesRoute
  '/channels/strategy': typeof AuthenticatedChannelsStrategyRoute
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
  '/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/providers/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
  '/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/providers/': typeof AuthenticatedProvidersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/providers/$providerId/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
<<<<<<< HEAD
=======
  '/channels': typeof AuthenticatedChannelsRouteWithChildren
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
  '/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/rates': typeof AuthenticatedRatesRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
<<<<<<< HEAD
  '/channels/channel-configs': typeof AuthenticatedChannelsChannelConfigsRoute
  '/channels/health': typeof AuthenticatedChannelsHealthRoute
  '/channels/routing-rules': typeof AuthenticatedChannelsRoutingRulesRoute
  '/channels/strategy': typeof AuthenticatedChannelsStrategyRoute
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
  '/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/providers/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
  '/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/providers': typeof AuthenticatedProvidersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/providers/$providerId/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/version': typeof VersionRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteWithChildren
  '/_authenticated/merchants': typeof AuthenticatedMerchantsRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRouteWithChildren
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/settlements': typeof AuthenticatedSettlementsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRouteWithChildren
  '/mfa/setup': typeof MfaSetupRoute
  '/mfa/verify': typeof MfaVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/channels/$channelId': typeof AuthenticatedChannelsChannelIdRoute
<<<<<<< HEAD
  '/_authenticated/channels/channel-configs': typeof AuthenticatedChannelsChannelConfigsRoute
  '/_authenticated/channels/health': typeof AuthenticatedChannelsHealthRoute
  '/_authenticated/channels/routing-rules': typeof AuthenticatedChannelsRoutingRulesRoute
  '/_authenticated/channels/strategy': typeof AuthenticatedChannelsStrategyRoute
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
  '/_authenticated/merchants/$merchantId': typeof AuthenticatedMerchantsMerchantIdRoute
  '/_authenticated/merchants/dashboard': typeof AuthenticatedMerchantsDashboardRoute
  '/_authenticated/providers/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
  '/_authenticated/settings/trusted-devices': typeof AuthenticatedSettingsTrustedDevicesRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/providers/': typeof AuthenticatedProvidersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/providers/$providerId/channels': typeof AuthenticatedProvidersProviderIdChannelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/version'
    | '/agents'
    | '/analytics'
    | '/channels'
    | '/merchants'
    | '/monitoring'
    | '/notifications'
    | '/providers'
    | '/rates'
    | '/risk'
    | '/settings'
    | '/settlements'
    | '/transactions'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/channels/$channelId'
<<<<<<< HEAD
    | '/channels/channel-configs'
    | '/channels/health'
    | '/channels/routing-rules'
    | '/channels/strategy'
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
    | '/merchants/$merchantId'
    | '/merchants/dashboard'
    | '/providers/channels'
    | '/settings/trusted-devices'
    | '/transactions/$id'
    | '/channels/'
    | '/providers/'
    | '/settings/'
    | '/transactions/'
    | '/providers/$providerId/channels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/version'
    | '/agents'
    | '/analytics'
    | '/merchants'
    | '/monitoring'
    | '/notifications'
    | '/providers'
    | '/rates'
    | '/risk'
    | '/settlements'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/'
    | '/channels/$channelId'
<<<<<<< HEAD
    | '/channels/channel-configs'
    | '/channels/health'
    | '/channels/routing-rules'
    | '/channels/strategy'
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
    | '/merchants/$merchantId'
    | '/merchants/dashboard'
    | '/providers/channels'
    | '/settings/trusted-devices'
    | '/transactions/$id'
    | '/channels'
    | '/providers'
    | '/settings'
    | '/transactions'
    | '/providers/$providerId/channels'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/version'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/channels'
    | '/_authenticated/merchants'
    | '/_authenticated/monitoring'
    | '/_authenticated/notifications'
    | '/_authenticated/providers'
    | '/_authenticated/rates'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/settlements'
    | '/_authenticated/transactions'
    | '/mfa/setup'
    | '/mfa/verify'
    | '/_authenticated/'
    | '/_authenticated/channels/$channelId'
<<<<<<< HEAD
    | '/_authenticated/channels/channel-configs'
    | '/_authenticated/channels/health'
    | '/_authenticated/channels/routing-rules'
    | '/_authenticated/channels/strategy'
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
    | '/_authenticated/merchants/$merchantId'
    | '/_authenticated/merchants/dashboard'
    | '/_authenticated/providers/channels'
    | '/_authenticated/settings/trusted-devices'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/channels/'
    | '/_authenticated/providers/'
    | '/_authenticated/settings/'
    | '/_authenticated/transactions/'
    | '/_authenticated/providers/$providerId/channels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VersionRoute: typeof VersionRoute
  MfaSetupRoute: typeof MfaSetupRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version': {
      id: '/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof VersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/mfa/verify': {
      id: '/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/setup': {
      id: '/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/mfa/setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settlements': {
      id: '/_authenticated/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof AuthenticatedSettlementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchants': {
      id: '/_authenticated/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AuthenticatedMerchantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/providers/': {
      id: '/_authenticated/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedTransactionsRoute
    }
    '/_authenticated/settings/trusted-devices': {
      id: '/_authenticated/settings/trusted-devices'
      path: '/trusted-devices'
      fullPath: '/settings/trusted-devices'
      preLoaderRoute: typeof AuthenticatedSettingsTrustedDevicesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/providers/channels': {
      id: '/_authenticated/providers/channels'
      path: '/channels'
      fullPath: '/providers/channels'
      preLoaderRoute: typeof AuthenticatedProvidersProviderIdChannelsRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
    '/_authenticated/merchants/dashboard': {
      id: '/_authenticated/merchants/dashboard'
      path: '/dashboard'
      fullPath: '/merchants/dashboard'
      preLoaderRoute: typeof AuthenticatedMerchantsDashboardRouteImport
      parentRoute: typeof AuthenticatedMerchantsRoute
    }
    '/_authenticated/merchants/$merchantId': {
      id: '/_authenticated/merchants/$merchantId'
      path: '/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof AuthenticatedMerchantsMerchantIdRouteImport
      parentRoute: typeof AuthenticatedMerchantsRoute
    }
<<<<<<< HEAD
    '/_authenticated/channels/strategy': {
      id: '/_authenticated/channels/strategy'
      path: '/strategy'
      fullPath: '/channels/strategy'
      preLoaderRoute: typeof AuthenticatedChannelsStrategyRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/routing-rules': {
      id: '/_authenticated/channels/routing-rules'
      path: '/routing-rules'
      fullPath: '/channels/routing-rules'
      preLoaderRoute: typeof AuthenticatedChannelsRoutingRulesRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/health': {
      id: '/_authenticated/channels/health'
      path: '/health'
      fullPath: '/channels/health'
      preLoaderRoute: typeof AuthenticatedChannelsHealthRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/channels/channel-configs': {
      id: '/_authenticated/channels/channel-configs'
      path: '/channel-configs'
      fullPath: '/channels/channel-configs'
      preLoaderRoute: typeof AuthenticatedChannelsChannelConfigsRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
    '/_authenticated/channels/$channelId': {
      id: '/_authenticated/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelsChannelIdRouteImport
      parentRoute: typeof AuthenticatedChannelsRoute
    }
    '/_authenticated/providers/$providerId/channels': {
      id: '/_authenticated/providers/$providerId/channels'
      path: '/$providerId/channels'
      fullPath: '/providers/$providerId/channels'
      preLoaderRoute: typeof AuthenticatedProvidersProviderIdChannelsRouteImport
      parentRoute: typeof AuthenticatedProvidersRoute
    }
  }
}

interface AuthenticatedChannelsRouteChildren {
  AuthenticatedChannelsChannelIdRoute: typeof AuthenticatedChannelsChannelIdRoute
<<<<<<< HEAD
  AuthenticatedChannelsChannelConfigsRoute: typeof AuthenticatedChannelsChannelConfigsRoute
  AuthenticatedChannelsHealthRoute: typeof AuthenticatedChannelsHealthRoute
  AuthenticatedChannelsRoutingRulesRoute: typeof AuthenticatedChannelsRoutingRulesRoute
  AuthenticatedChannelsStrategyRoute: typeof AuthenticatedChannelsStrategyRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
}

const AuthenticatedChannelsRouteChildren: AuthenticatedChannelsRouteChildren = {
  AuthenticatedChannelsChannelIdRoute: AuthenticatedChannelsChannelIdRoute,
<<<<<<< HEAD
  AuthenticatedChannelsChannelConfigsRoute:
    AuthenticatedChannelsChannelConfigsRoute,
  AuthenticatedChannelsHealthRoute: AuthenticatedChannelsHealthRoute,
  AuthenticatedChannelsRoutingRulesRoute:
    AuthenticatedChannelsRoutingRulesRoute,
  AuthenticatedChannelsStrategyRoute: AuthenticatedChannelsStrategyRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
}

const AuthenticatedChannelsRouteWithChildren =
  AuthenticatedChannelsRoute._addFileChildren(
    AuthenticatedChannelsRouteChildren,
  )

interface AuthenticatedMerchantsRouteChildren {
  AuthenticatedMerchantsMerchantIdRoute: typeof AuthenticatedMerchantsMerchantIdRoute
  AuthenticatedMerchantsDashboardRoute: typeof AuthenticatedMerchantsDashboardRoute
}

const AuthenticatedMerchantsRouteChildren: AuthenticatedMerchantsRouteChildren =
  {
    AuthenticatedMerchantsMerchantIdRoute:
      AuthenticatedMerchantsMerchantIdRoute,
    AuthenticatedMerchantsDashboardRoute: AuthenticatedMerchantsDashboardRoute,
  }

const AuthenticatedMerchantsRouteWithChildren =
  AuthenticatedMerchantsRoute._addFileChildren(
    AuthenticatedMerchantsRouteChildren,
  )

interface AuthenticatedProvidersRouteChildren {
  AuthenticatedProvidersProviderIdChannelsRoute: typeof AuthenticatedProvidersProviderIdChannelsRoute
<<<<<<< HEAD
  AuthenticatedProvidersIndexRoute: typeof AuthenticatedProvidersIndexRoute
  AuthenticatedProvidersProviderIdChannelsRoute: typeof AuthenticatedProvidersProviderIdChannelsRoute
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
}

const AuthenticatedProvidersRouteChildren: AuthenticatedProvidersRouteChildren =
  {
<<<<<<< HEAD
    AuthenticatedProvidersProviderIdChannelsRoute: AuthenticatedProvidersProviderIdChannelsRoute,
    AuthenticatedProvidersIndexRoute: AuthenticatedProvidersIndexRoute,
=======
>>>>>>> d8fb1e2 (feat(channels): pre-execute 骨架、types/stub、adapter、路由就位)
    AuthenticatedProvidersProviderIdChannelsRoute:
      AuthenticatedProvidersProviderIdChannelsRoute,
  }

const AuthenticatedProvidersRouteWithChildren =
  AuthenticatedProvidersRoute._addFileChildren(
    AuthenticatedProvidersRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsTrustedDevicesRoute: typeof AuthenticatedSettingsTrustedDevicesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsTrustedDevicesRoute:
    AuthenticatedSettingsTrustedDevicesRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedTransactionsRouteChildren {
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedTransactionsRouteChildren: AuthenticatedTransactionsRouteChildren =
  {
    AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
    AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  }

const AuthenticatedTransactionsRouteWithChildren =
  AuthenticatedTransactionsRoute._addFileChildren(
    AuthenticatedTransactionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRouteWithChildren
  AuthenticatedMerchantsRoute: typeof AuthenticatedMerchantsRouteWithChildren
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRouteWithChildren
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSettlementsRoute: typeof AuthenticatedSettlementsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRouteWithChildren,
  AuthenticatedMerchantsRoute: AuthenticatedMerchantsRouteWithChildren,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRouteWithChildren,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSettlementsRoute: AuthenticatedSettlementsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VersionRoute: VersionRoute,
  MfaSetupRoute: MfaSetupRoute,
  MfaVerifyRoute: MfaVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
